name: Exercise_2 

on:

  workflow_dispatch:

jobs:
 
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node_hello:latest
    - name: run & test Container
      run: docker run -itd --name node_hello -p 3000:3000  node_hello:latest
    - run: sleep 5 && curl localhost:3000
    - name: change image name 
      run: docker tag node_hello:latest ddriham/node-hello:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: docker push ddriham/node-hello:latest
